import "./globals.css";
import {Inter} from "next/font/google";
import {cx} from "class-variance-authority";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={cx(inter.className, "bg-emerald-900")}>
        <main className="flex min-h-screen flex-col items-center justify-center p-24">
          <h1 className="text-6xl font-bold mb-8">PomoDuo</h1>

          {children}
        </main>
      </body>
    </html>
  );
}
